name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lilyanntoma/my-docker-jokes:v1
    - name: Docker Push
      run: docker push lilyanntoma/my-docker-jokes:v1
